### ISSUE TITLE
Add an option to open links in newtab

### ISSUE THREAD

**Issue by sijad** [sijad/flarum-ext-links#1]

**Comment by Alir3z4** [comment]
Normally when creating link from admin area, being able to pass the value of html tag `target` would be enough.

**Comment by sijad** [comment]
as we just need add `_blank` as target attribute, I was thinking about adding a check box to that form

**Comment by Alir3z4** [comment]
Forgive me for my abstract/generic thinking, I'm more of a backend developer and my frontend knowledge is not that detail covered.

Having a checkbox makes more sense of course.
Hope to see this feature implemented soon.

**Comment by sijad** [comment]
fixed in https://github.com/sijad/flarum-ext-links/commit/6c84357d2d5dae25bb482ddd3b0bd6436ea39b0e
