### ISSUE TITLE
Blocking the return

### ISSUE THREAD

**Issue by youhosi** [sijad/flarum-ext-links#8]
Hello, could you add a blocking return on the forum? It would increase security :)

```
rel="nofollow noreferrer"
```

And when you would finish the todo list?

**Comment by sijad** [comment]
there should be an option to let admin add those, some links are internal and probably shouldn't have those rel. `noopener` also should be added in some cases.

> And when you would finish the todo list?

probably after beta 8 release. but please feel free to send PR.

**Comment by youhosi** [comment]
In that case, he would only add to external links "nofollow noreferrer"
